# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import project_pb2 as project__pb2


class ProjectStub(object):
    """*
    Paddle's project API service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrintMessage = channel.unary_unary(
                '/io.paddle.plugin.interop.Project/PrintMessage',
                request_serializer=project__pb2.PrintRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetConfigurationSpecification = channel.unary_unary(
                '/io.paddle.plugin.interop.Project/GetConfigurationSpecification',
                request_serializer=project__pb2.GetConfigSpecRequest.SerializeToString,
                response_deserializer=project__pb2.CompositeSpecNode.FromString,
                )
        self.UpdateConfigurationSpecification = channel.unary_unary(
                '/io.paddle.plugin.interop.Project/UpdateConfigurationSpecification',
                request_serializer=project__pb2.UpdateConfigSpecRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class ProjectServicer(object):
    """*
    Paddle's project API service definition.
    """

    def PrintMessage(self, request, context):
        """*
        Prints message to the terminal associated with specified project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfigurationSpecification(self, request, context):
        """*
        Returns configuration specification of specified project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfigurationSpecification(self, request, context):
        """*
        Updates configuration specification of specified project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProjectServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrintMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PrintMessage,
                    request_deserializer=project__pb2.PrintRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetConfigurationSpecification': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfigurationSpecification,
                    request_deserializer=project__pb2.GetConfigSpecRequest.FromString,
                    response_serializer=project__pb2.CompositeSpecNode.SerializeToString,
            ),
            'UpdateConfigurationSpecification': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfigurationSpecification,
                    request_deserializer=project__pb2.UpdateConfigSpecRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'io.paddle.plugin.interop.Project', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Project(object):
    """*
    Paddle's project API service definition.
    """

    @staticmethod
    def PrintMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/io.paddle.plugin.interop.Project/PrintMessage',
            project__pb2.PrintRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConfigurationSpecification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/io.paddle.plugin.interop.Project/GetConfigurationSpecification',
            project__pb2.GetConfigSpecRequest.SerializeToString,
            project__pb2.CompositeSpecNode.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateConfigurationSpecification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/io.paddle.plugin.interop.Project/UpdateConfigurationSpecification',
            project__pb2.UpdateConfigSpecRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
